cacic_common_homepage:
    pattern:  /
    defaults: { _controller: CacicCommonBundle:Default:index }

cacic_common_login:
    pattern:  /login
    defaults: { _controller: CacicCommonBundle:Security:login }

cacic_common_login_check:
    pattern:  /authenticate

cacic_common_logout:
    pattern: /logout

cacic_common_instalador:
    pattern:  /instalador
    defaults: { _controller: CacicCommonBundle:Default:instalador }

cacic_usuario_index:
    pattern:  /usuario/{page}
    defaults: { _controller: CacicCommonBundle:Usuario:index, page: 1 }
    requirements:
        page: \d+

cacic_usuario_trocar_senha:
    pattern:  /usuario/trocarsenha
    defaults: { _controller: CacicCommonBundle:Usuario:trocarsenha}

cacic_usuario_cadastrar:
    pattern:  /usuario/cadastrar
    defaults: { _controller: CacicCommonBundle:Usuario:cadastrar}

cacic_usuario_editar:
    pattern:  /usuario/editar/{idUsuario}
    defaults: { _controller: CacicCommonBundle:Usuario:editar, idUsuario: null}
    requirements:
        idUsuario: \d+

cacic_usuario_excluir:
    pattern:  /usuario/excluir
    defaults: { _controller: CacicCommonBundle:Usuario:excluir}


cacic_usuario_recuperar_senha:
    pattern:  /usuario/recuperarsenha
    defaults: { _controller: CacicCommonBundle:Usuario:recuperarsenha}

cacic_local_index:
    pattern:  /local/{page}
    defaults: { _controller: CacicCommonBundle:Local:index, page: 1 }
    requirements:
        page: \d+

cacic_local_cadastrar:
    pattern:  /local/cadastrar
    defaults: { _controller: CacicCommonBundle:Local:cadastrar}

cacic_local_editar:
    pattern:  /local/editar/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:editar}
    requirements:
        idLocal: \d+

cacic_local_excluir:
    pattern:  /local/excluir
    defaults: { _controller: CacicCommonBundle:Local:excluir}

cacic_local_redesassociadas:
    pattern:  /local/redes/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:redes}
    requirements:
        idLocal: \d+

cacic_local_usuariosassociados:
    pattern:  /local/usuarios/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:usuarios}
    requirements:
        idLocal: \d+

cacic_local_configuracoes:
    pattern:  /local/configuracoes/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:configuracoes}
    requirements:
        idLocal: \d+

cacic_servidorautenticacao_index:
    pattern: /servidorautenticacao/{page}
    defaults: {_controller: CacicCommonBundle:ServidorAutenticacao:index, page: 1 }
    requirements:
        page: \d+

cacic_servidorautenticacao_cadastrar:
    pattern: /servidorautenticacao/cadastrar
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:cadastrar}

cacic_servidorautenticacao_editar:
    pattern:  /servidorautenticacao/editar/{idServidorAutenticacao}
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:editar}
    requirements:
        idLocal: \d+

cacic_servidorautenticacao_excluir:
    pattern:  /servidorautenticacao/excluir
    defaults: { _controller: CacicCommonBundle:servidorautenticacao:excluir}

cacic_servidorautenticacao_redesassociadas:
    pattern:  /servidorautenticacao/redes/{idServidorAutenticacao}
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:redes}
    requirements:
        idLocal: \d+

cacic_subrede_index:
    pattern: /subrede/{page}
    defaults: {_controller: CacicCommonBundle:Rede:index, page: 1 }
    requirements:
        page: \d+

cacic_subrede_cadastrar:
    pattern: /subrede/cadastrar
    defaults: { _controller: CacicCommonBundle:Rede:cadastrar}

cacic_subrede_editar:
    pattern:  /subrede/editar/{idRede}
    defaults: { _controller: CacicCommonBundle:Rede:editar}
    requirements:
        idRede: \d+

cacic_subrede_excluir:
    pattern:  /subrede/excluir
    defaults: { _controller: CacicCommonBundle:Rede:excluir}


cacic_aplicativo_index:
    pattern: /aplicativo/{page}
    defaults: {_controller: CacicCommonBundle:Aplicativo:index, page: 1 }
    requirements:
        page: \d+

cacic_aplicativo_cadastrar:
    pattern: /aplicativo/cadastrar
    defaults: { _controller: CacicCommonBundle:Aplicativo:cadastrar}

cacic_aplicativo_editar:
    pattern:  /aplicativo/editar/{idAplicativo}
    defaults: { _controller: CacicCommonBundle:Aplicativo:editar}
    requirements:
        idAplicativo: \d+

cacic_aplicativo_excluir:
    pattern:  /aplicativo/excluir
    defaults: { _controller: CacicCommonBundle:Aplicativo:excluir}


cacic_tiposoftware_index:
    pattern: /tiposoftware/{page}
    defaults: {_controller: CacicCommonBundle:TipoSoftware:index, page: 1 }
    requirements:
        page: \d+

cacic_tiposoftware_cadastrar:
    pattern: /tiposoftware/cadastrar
    defaults: { _controller: CacicCommonBundle:TipoSoftware:cadastrar}

cacic_tiposoftware_editar:
    pattern:  /tiposoftware/editar/{idTipoSoftware}
    defaults: { _controller: CacicCommonBundle:TipoSoftware:editar}
    requirements:
        idTipoSoftware: \d+

cacic_tiposoftware_excluir:
    pattern:  /tiposoftware/excluir
    defaults: { _controller: CacicCommonBundle:TipoSoftware:excluir}

cacic_sistemaoperacional_index:
    pattern: /sistemaoperacional/{page}
    defaults: {_controller: CacicCommonBundle:So:index, page: 1 }
    requirements:
        page: \d+

cacic_sistemaoperacional_cadastrar:
    pattern: /sistemaoperacional/cadastrar
    defaults: { _controller: CacicCommonBundle:So:cadastrar}

cacic_sistemaoperacional_editar:
    pattern:  /sistemaoperacional/editar/{idSo}
    defaults: { _controller: CacicCommonBundle:So:editar}
    requirements:
        idSo: \d+

cacic_sistemaoperacional_excluir:
    pattern:  /sistemaoperacional/excluir
    defaults: { _controller: CacicCommonBundle:So:excluir}

cacic_software_index:
    pattern: /software/{page}
    defaults: {_controller: CacicCommonBundle:Software:index, page: 1 }
    requirements:
        page: \d+

cacic_software_cadastrar:
    pattern: /software/cadastrar
    defaults: { _controller: CacicCommonBundle:Software:cadastrar}

cacic_software_editar:
    pattern:  /software/editar/{idSoftware}
    defaults: { _controller: CacicCommonBundle:Software:editar}
    requirements:
        idSoftware: \d+

cacic_software_excluir:
    pattern:  /software/excluir
    defaults: { _controller: CacicCommonBundle:Software:excluir}

cacic_configuracaopadrao_index:
    pattern: /configuracaopadrao
    defaults: { _controller: CacicCommonBundle:ConfiguracaoPadrao:index}
cacic_configuracao_padrao:
    pattern: /configuracao/padrao
    defaults: { _controller: CacicCommonBundle:Configuracao:padrao}

cacic_configuracao_agente:
    pattern: /configuracao/agente
    defaults: { _controller: CacicCommonBundle:Configuracao:agente}

cacic_configuracao_gerente:
    pattern: /configuracao/gerente
    defaults: { _controller: CacicCommonBundle:Configuracao:gerente}

cacic_usbdevice_index:
    pattern: /usbdevice/{page}
    defaults: {_controller: CacicCommonBundle:UsbDevice:index, page: 1 }
    requirements:
        page: \d+

cacic_usbdevice_cadastrar:
    pattern: /usbdevice/cadastrar
    defaults: { _controller: CacicCommonBundle:UsbDevice:cadastrar}

cacic_usbdevice_editar:
    pattern:  /usbdevice/editar/{idUsbDevice}
    defaults: { _controller: CacicCommonBundle:UsbDevice:editar}
    requirements:
        idUsbDevice: \d+

cacic_usbdevice_excluir:
    pattern:  /usbdevice/excluir
    defaults: { _controller: CacicCommonBundle:UsbDevice:excluir}


