cacic_common_homepage:
    pattern:  /
    defaults: { _controller: CacicCommonBundle:Default:index }

cacic_common_login:
    pattern:  /login
    defaults: { _controller: CacicCommonBundle:Security:login }

cacic_common_login_check:
    pattern:  /authenticate

cacic_common_logout:
    pattern: /logout

cacic_common_instalador:
    pattern:  /instalador
    defaults: { _controller: CacicCommonBundle:Default:instalador }

cacic_usuario_index:
    pattern:  /usuario/{page}
    defaults: { _controller: CacicCommonBundle:Usuario:index, page: 1 }
    requirements:
        page: \d+

cacic_usuario_trocar_senha:
    pattern:  /usuario/trocarsenha
    defaults: { _controller: CacicCommonBundle:Usuario:trocarsenha}

cacic_usuario_cadastrar:
    pattern:  /usuario/cadastrar
    defaults: { _controller: CacicCommonBundle:Usuario:cadastrar}

cacic_usuario_editar:
    pattern:  /usuario/editar/{idUsuario}
    defaults: { _controller: CacicCommonBundle:Usuario:editar, idUsuario: null}
    requirements:
        idUsuario: \d+

cacic_usuario_excluir:
    pattern:  /usuario/excluir
    defaults: { _controller: CacicCommonBundle:Usuario:excluir}


cacic_usuario_recuperar_senha:
    pattern:  /usuario/recuperarsenha
    defaults: { _controller: CacicCommonBundle:Usuario:recuperarsenha}

cacic_local_index:
    pattern:  /local/{page}
    defaults: { _controller: CacicCommonBundle:Local:index, page: 1 }
    requirements:
        page: \d+

cacic_local_cadastrar:
    pattern:  /local/cadastrar
    defaults: { _controller: CacicCommonBundle:Local:cadastrar}

cacic_local_editar:
    pattern:  /local/editar/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:editar}
    requirements:
        idLocal: \d+

cacic_local_excluir:
    pattern:  /local/excluir
    defaults: { _controller: CacicCommonBundle:Local:excluir}

cacic_local_redesassociadas:
    pattern:  /local/redes/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:redes}
    requirements:
        idLocal: \d+

cacic_local_usuariosassociados:
    pattern:  /local/usuarios/{idLocal}
    defaults: { _controller: CacicCommonBundle:Local:usuarios}
    requirements:
        idLocal: \d+

cacic_servidorautenticacao_index:
    pattern: /servidorautenticacao/{page}
    defaults: {_controller: CacicCommonBundle:ServidorAutenticacao:index, page: 1 }
    requirements:
        page: \d+

cacic_servidorautenticacao_cadastrar:
    pattern: /servidorautenticacao/cadastrar
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:cadastrar}

cacic_servidorautenticacao_editar:
    pattern:  /servidorautenticacao/editar/{idServidorAutenticacao}
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:editar}
    requirements:
        idLocal: \d+

cacic_servidorautenticacao_excluir:
    pattern:  /servidorautenticacao/excluir
    defaults: { _controller: CacicCommonBundle:servidorautenticacao:excluir}

cacic_servidorautenticacao_redesassociadas:
    pattern:  /servidorautenticacao/redes/{idServidorAutenticacao}
    defaults: { _controller: CacicCommonBundle:ServidorAutenticacao:redes}
    requirements:
        idLocal: \d+

cacic_subrede_index:
    pattern: /subrede/{page}
    defaults: {_controller: CacicCommonBundle:Rede:index, page: 1 }
    requirements:
        page: \d+

cacic_subrede_cadastrar:
    pattern: /subrede/cadastrar
    defaults: { _controller: CacicCommonBundle:Rede:cadastrar}

cacic_subrede_editar:
    pattern:  /subrede/editar/{idRede}
    defaults: { _controller: CacicCommonBundle:Rede:editar}
    requirements:
        idRede: \d+

cacic_subrede_excluir:
    pattern:  /subrede/excluir
    defaults: { _controller: CacicCommonBundle:Rede:excluir}


cacic_perfilaplicativomonitorado_index:
    pattern: /perfilaplicativomonitorado/{page}
    defaults: {_controller: CacicCommonBundle:PerfilAplicativoMonitorado:index, page: 1 }
    requirements:
        page: \d+

cacic_perfilaplicativomonitorado_cadastrar:
    pattern: /perfilaplicativomonitorado/cadastrar
    defaults: { _controller: CacicCommonBundle:PerfilAplicativoMonitorado:cadastrar}

cacic_perfilaplicativomonitorado_editar:
    pattern:  /perfilaplicativomonitorado/editar/{idAplicativo}
    defaults: { _controller: CacicCommonBundle:PerfilAplicativoMonitorado:editar}
    requirements:
        idAplicativo: \d+

cacic_perfilaplicativomonitorado_excluir:
    pattern:  /perfilaplicativomonitorado/excluir
    defaults: { _controller: CacicCommonBundle:PerfilAplicativoMonitorado:excluir}
