parameters:
#    cacic_common.example.class: Cacic\CommonBundle\Example

services:
#    cacic_common.example:
#        class: %cacic_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
