parameters:
#    cacic_relatorio.example.class: Cacic\RelatorioBundle\Example

services:
#    cacic_relatorio.example:
#        class: %cacic_relatorio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
