ConfiguracoesPadrao:
    type: entity
    table: configuracoes_padrao
    fields:
        idConfiguracaoPadrao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_configuracao_padrao
            generator:
                strategy: IDENTITY
        inExibeErrosCriticos:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: in_exibe_erros_criticos
        inExibeBandeja:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: in_exibe_bandeja
        nuExecApos:
            type: integer
            unsigned: false
            nullable: true
            column: nu_exec_apos
        nuRelMaxlinhas:
            type: smallint
            nullable: true
            column: nu_rel_maxlinhas
        nmOrganizacao:
            type: string
            length: 150
            fixed: true
            nullable: true
            column: nm_organizacao
        nuTimeoutSrcacic:
            type: boolean
            nullable: false
            column: nu_timeout_srcacic
        nuIntervaloExec:
            type: integer
            unsigned: false
            nullable: true
            column: nu_intervalo_exec
        nuIntervaloRenovacaoPatrim:
            type: integer
            unsigned: false
            nullable: true
            column: nu_intervalo_renovacao_patrim
        teSenhaAdmAgente:
            type: string
            length: 30
            fixed: true
            nullable: true
            column: te_senha_adm_agente
        teServUpdatesPadrao:
            type: string
            length: 60
            fixed: true
            nullable: true
            column: te_serv_updates_padrao
        teServCacicPadrao:
            type: string
            length: 60
            fixed: true
            nullable: true
            column: te_serv_cacic_padrao
        teEnderecosMacInvalidos:
            type: text
            nullable: true
            column: te_enderecos_mac_invalidos
        teJanelasExcecao:
            type: text
            nullable: true
            column: te_janelas_excecao
        csAbreJanelaPatr:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: cs_abre_janela_patr
        idDefaultBodyBgcolor:
            type: string
            length: 10
            fixed: true
            nullable: false
            column: id_default_body_bgcolor
        teExibeGraficos:
            type: string
            length: 100
            fixed: true
            nullable: false
            column: te_exibe_graficos
        nuPortaSrcacic:
            type: string
            length: 5
            fixed: true
            nullable: false
            column: nu_porta_srcacic
        nuResolucaoGraficoH:
            type: smallint
            nullable: false
            column: nu_resolucao_grafico_h
        nuResolucaoGraficoW:
            type: smallint
            nullable: false
            column: nu_resolucao_grafico_w
    lifecycleCallbacks: {  }
