<?php

namespace Cacic\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfiguracaoLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfiguracaoLocalRepository extends EntityRepository
{
	/**
	 * 
	 * Lista as configurações do Local informado
	 * @param int $idLocal
	 * @return array
	 */
	public function listarPorLocal( $idLocal )
	{
		$_dql = "SELECT cl.vlConfiguracao, cp.idConfiguracao, cp.nmConfiguracao
				FROM CacicCommonBundle:ConfiguracaoLocal cl
				JOIN cl.idConfiguracao cp
				WHERE cl.idLocal = :idLocal";

        return $this->getEntityManager()
        			->createQuery( $_dql )
        			->setParameter( 'idLocal', $idLocal )
        			->getArrayResult();
	}
	
	/**
	 * 
	 * Recupera um array na forma [idConfiguracao] => [vlConfiguracao]
	 */
	public function getArrayChaveValor( $idLocal )
	{
		$configuracoes = $this->listarPorLocal( $idLocal );
		$return = array();
		
		foreach ( $configuracoes as $config )
		{
			$return[ $config['idConfiguracao'] ] = $config[ 'vlConfiguracao' ];
		}
		
		return $return;
	}
}
