jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:        password
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        bancodedados:
            entity: { class: Cacic\CommonBundle\Entity\Usuarios, property: nm_usuario_acesso }

    firewalls:
        login:
            pattern:  ^/login$
            security: false
        usuario:
             pattern: ^/usuario*
             security: false
        main:
            form_login:
                default_target_path: /login
                always_use_default_target_path: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }