Cacic\CommonBundle\Entity\AcaoExcecao:
    type: entity
    table: acao_excecao
    fields:
        idAcaoExcecao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_acao_excecao
            generator:
                strategy: IDENTITY
        teNodeAddress:
            type: string
            length: 17
            fixed: true
            nullable: false
            column: te_node_address
    manyToOne:
        idAcao:
            targetEntity: Acao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_acao:
                    referencedColumnName: id_acao
            orphanRemoval: false
        idRede:
            targetEntity: Rede
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rede:
                    referencedColumnName: id_rede
            orphanRemoval: false
    lifecycleCallbacks: {  }
