Cacic\CommonBundle\Entity\Aplicativo:
    type: entity
    table: aplicativo
    fields:
        idAplicativo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_aplicativo
            generator:
                strategy: IDENTITY
        nmAplicativo:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nm_aplicativo
        csCarInstW9x:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: cs_car_inst_w9x
        teCarInstW9x:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_car_inst_w9x
        csCarVerW9x:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: cs_car_ver_w9x
        teCarVerW9x:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_car_ver_w9x
        csCarInstWnt:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: cs_car_inst_wnt
        teCarInstWnt:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_car_inst_wnt
        csCarVerWnt:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: cs_car_ver_wnt
        teCarVerWnt:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_car_ver_wnt
        csIdeLicenca:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: cs_ide_licenca
        teIdeLicenca:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_ide_licenca
        dtAtualizacao:
            type: datetime
            nullable: true
            column: dt_atualizacao
        teArqVerEngW9x:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_arq_ver_eng_w9x
        teArqVerPatW9x:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_arq_ver_pat_w9x
        teArqVerEngWnt:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_arq_ver_eng_wnt
        teArqVerPatWnt:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_arq_ver_pat_wnt
        teDirPadraoW9x:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_dir_padrao_w9x
        teDirPadraoWnt:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_dir_padrao_wnt
        teDescritivo:
            type: text
            nullable: true
            column: te_descritivo
        inDisponibilizaInfo:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: in_disponibiliza_info
        inDisponibilizaInfoUsuarioComum:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: in_disponibiliza_info_usuario_comum
        dtRegistro:
            type: datetime
            nullable: true
            column: dt_registro
    manyToMany:
        idRede:
            targetEntity: Rede
            cascade: {  }
            mappedBy: idAplicativo
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        idSo:
            targetEntity: So
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_so:
                    referencedColumnName: id_so
            orphanRemoval: false
    lifecycleCallbacks: {  }
