Cacic\CommonBundle\Entity\Aquisicao:
    type: entity
    table: aquisicao
    fields:
        idAquisicao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_aquisicao
            generator:
                strategy: IDENTITY
        dtAquisicao:
            type: date
            nullable: true
            column: dt_aquisicao
        nrProcesso:
            type: string
            length: 11
            fixed: true
            nullable: true
            column: nr_processo
        nmEmpresa:
            type: string
            length: 45
            fixed: true
            nullable: true
            column: nm_empresa
        nmProprietario:
            type: string
            length: 45
            fixed: true
            nullable: true
            column: nm_proprietario
        nrNotafiscal:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: nr_notafiscal
    lifecycleCallbacks: {  }
