Cacic\CommonBundle\Entity\ConfiguracaoPadrao:
    type: entity
    table: configuracao_padrao
    repositoryClass: Cacic\CommonBundle\Entity\ConfiguracaoPadraoRepository
    fields:
        idConfiguracaoPadrao:
            id: true
            type: smallint
            nullable: false
            column: id_configuracao_padrao
            generator:
                strategy: IDENTITY
        sgVariavel:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: sg_variavel
        nmConfiguracao:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nm_configuracao
        vlConfiguracao:
            type: text
            nullable: true
            column: vl_configuracao
    lifecycleCallbacks: {  }
