Cacic\CommonBundle\Entity\SoftwareEstacao:
    type: entity
    table: software_estacao
    repositoryClass: Cacic\CommonBundle\Entity\SoftwareEstacaoRepository
    id:
        nrPatrimonio:
            id: true
            type: string
            length: 20
            fixed: true
            nullable: false
            column: nr_patrimonio
        idSoftware:
            associationKey: true
    fields:
        nmComputador:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: nm_computador
        dtAutorizacao:
            type: date
            nullable: true
            column: dt_autorizacao
        nrProcesso:
            type: string
            length: 11
            fixed: true
            nullable: true
            column: nr_processo
        dtExpiracaoInstalacao:
            type: date
            nullable: true
            column: dt_expiracao_instalacao
        idAquisicaoParticular:
            type: integer
            unsigned: false
            nullable: true
            column: id_aquisicao_particular
        dtDesinstalacao:
            type: date
            nullable: true
            column: dt_desinstalacao
        teObservacao:
            type: string
            length: 90
            fixed: false
            nullable: true
            column: te_observacao
        nrPatrDestino:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: nr_patr_destino
    manyToOne:
        idSoftware:
            targetEntity: Software
            cascade: {  }
            mappedBy: null
            inversedBy: estacoes
            joinColumns:
                id_software:
                    referencedColumnName: id_software
            orphanRemoval: false
    lifecycleCallbacks: {  }
