Cacic\CommonBundle\Entity\Uorg:
    type: entity
    table: uorg
    repositoryClass: Cacic\CommonBundle\Entity\UorgRepository
    fields:
        idUorg:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_uorg
            generator:
                strategy: IDENTITY
        nmUorg:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: nm_uorg
        teEndereco:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: te_endereco
        teBairro:
            type: string
            length: 30
            fixed: true
            nullable: true
            column: te_bairro
        teCidade:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: te_cidade
        teUf:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: te_uf
        nmResponsavel:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: nm_responsavel
        teResponsavelEmail:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: te_responsavel_email
        numResponsavelTel1:
            type: string
            length: 10
            fixed: true
            nullable: true
            column: nu_responsavel_tel1
        numResponsavelTel2:
            type: string
            length: 10
            fixed: true
            nullable: true
            column: nu_responsavel_tel2
    oneToMany:
        uorgFilhas:
            targetEntity: Cacic\CommonBundle\Entity\Uorg
            mappedBy: uorgPai
    manyToOne:
        uorgPai:
            targetEntity: Cacic\CommonBundle\Entity\Uorg
            inversedBy: uorgFilhas
            joinColumns:
                id_uorg_pai:
                    referencedColumnName: id_uorg
    lifecycleCallbacks: {  }
