Cacic\CommonBundle\Entity\Usuario:
    type: entity
    table: usuario
    repositoryClass: Cacic\CommonBundle\Entity\UsuarioRepository
    fields:
        idUsuario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
            generator:
                strategy: IDENTITY
        idUsuarioLdap:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: id_usuario_ldap
        nmUsuarioAcesso:
            type: string
            length: 20
            fixed: true
            nullable: false
            column: nm_usuario_acesso
        nmUsuarioCompleto:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: nm_usuario_completo
        nmUsuarioCompletoLdap:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: nm_usuario_completo_ldap
        teSenha:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: te_senha
        dtLogIn:
            type: datetime
            nullable: true
            column: dt_log_in
        teEmailsContato:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_emails_contato
        teTelefonesContato:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_telefones_contato
        teLocaisSecundarios:
            type: text
            nullable: true
            column: te_locais_secundarios
    manyToOne:
        idLocal:
            targetEntity: Local
            cascade: {  }
            mappedBy: null
            inversedBy: usuarios
            joinColumns:
                id_local:
                    referencedColumnName: id_local
            orphanRemoval: false
        idServidorAutenticacao:
            targetEntity: ServidorAutenticacao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_servidor_autenticacao:
                    referencedColumnName: id_servidor_autenticacao
            orphanRemoval: false
        idGrupoUsuario:
            targetEntity: GrupoUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_grupo_usuario:
                    referencedColumnName: id_grupo_usuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
