parameters:
    database_driver: pdo_pgsql
    database_host: null
    database_port: 5433
    database_name: cacic
    database_user: www-data
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: pt_BR
    secret: e410b10b0cdc810ea6bb943caa542bb42b3
    database_path: null
