Cacic\CommonBundle\Entity\Acao:
    type: entity
    repositoryClass: Cacic\CommonBundle\Entity\AcaoRepository
    table: acao
    fields:
        idAcao:
            id: true
            type: string
            length: 30
            fixed: false
            nullable: false
            column: id_acao
            generator:
                strategy: IDENTITY
        teDescricaoBreve:
            type: string
            length: 100
            fixed: false
            nullable: true
            column: te_descricao_breve
        teDescricao:
            type: text
            nullable: true
            column: te_descricao
        teNomeCurtoModulo:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: te_nome_curto_modulo
        dtHrAlteracao:
            type: datetime
            nullable: true
            column: dt_hr_alteracao
        csOpcional:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: cs_opcional
    oneToMany:
        redes:
            targetEntity: AcaoRede
            mappedBy: acao
    lifecycleCallbacks: {  }
