Cacic\CommonBundle\Entity\Ateste:
    type: entity
    table: ateste
    repositoryClass: Cacic\CommonBundle\Entity\AtesteRepository
    fields:
        idAteste:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_ateste
            generator:
                strategy: IDENTITY
        descricao:
            type: text
            nullable: true
            column: descricao_ateste
        detalhes:
            type: text
            nullable: true
            column: detalhes
        atestado:
            type: boolean
            nullable: false
            column: atestado
        data:
            type: datetime
            nullable: false
            column: data
        qualidadeServico:
            type: text
            nullable: true
            column: qualidade_servico
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false