Cacic\CommonBundle\Entity\CollectDefClass:
    type: entity
    table: collect_def_class
    fields:
        idCollectDefClass:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_collect_def_class
            generator:
                strategy: IDENTITY
        teWhereClause:
            type: text
            nullable: true
            column: te_where_clause
    manyToOne:
        idAcao:
            targetEntity: Acao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_acao:
                    referencedColumnName: id_acao
            orphanRemoval: false
        idClass:
            targetEntity: Classe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class:
                    referencedColumnName: id_class
            orphanRemoval: false
    lifecycleCallbacks: {  }
