Cacic\CommonBundle\Entity\ConfiguracaoLocal:
    type: entity
    table: configuracao_local
    repositoryClass: Cacic\CommonBundle\Entity\ConfiguracaoLocalRepository
    id:
        idLocal:
            associationKey: true
    fields:
        teNotificarMudancasEmails:
            type: text
            nullable: true
            column: te_notificar_mudancas_emails
        teNotificarMudancasProperties:
            type: text
            nullable: false
            column: te_notificar_mudancas_properties
        teNotificarUtilizacaoUsb:
            type: text
            nullable: true
            column: te_notificar_utilizacao_usb
        inExibeErrosCriticos:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: in_exibe_erros_criticos
        inExibeBandeja:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: in_exibe_bandeja
        nuExecApos:
            type: integer
            unsigned: false
            nullable: false
            column: nu_exec_apos
        dtHrAlteracaoPatrimInterface:
            type: datetime
            nullable: true
            column: dt_hr_alteracao_patrim_interface
        dtHrAlteracaoPatrimUon1:
            type: datetime
            nullable: true
            column: dt_hr_alteracao_patrim_uon1
        dtHrAlteracaoPatrimUon1a:
            type: datetime
            nullable: true
            column: dt_hr_alteracao_patrim_uon1a
        dtHrAlteracaoPatrimUon2:
            type: datetime
            nullable: true
            column: dt_hr_alteracao_patrim_uon2
        dtHrColetaForcada:
            type: datetime
            nullable: true
            column: dt_hr_coleta_forcada
        teNotificarMudancaPatrim:
            type: text
            nullable: true
            column: te_notificar_mudanca_patrim
        nmOrganizacao:
            type: string
            length: 150
            fixed: true
            nullable: true
            column: nm_organizacao
        nuTimeoutSrcacic:
            type: boolean
            nullable: false
            column: nu_timeout_srcacic
        nuIntervaloExec:
            type: integer
            unsigned: false
            nullable: false
            column: nu_intervalo_exec
        nuIntervaloRenovacaoPatrim:
            type: integer
            unsigned: false
            nullable: true
            column: nu_intervalo_renovacao_patrim
        teSenhaAdmAgente:
            type: string
            length: 30
            fixed: true
            nullable: false
            column: te_senha_adm_agente
        teServUpdatesPadrao:
            type: string
            length: 60
            fixed: true
            nullable: true
            column: te_serv_updates_padrao
        teServCacicPadrao:
            type: string
            length: 60
            fixed: true
            nullable: true
            column: te_serv_cacic_padrao
        teEnderecosMacInvalidos:
            type: text
            nullable: true
            column: te_enderecos_mac_invalidos
        teJanelasExcecao:
            type: text
            nullable: true
            column: te_janelas_excecao
        teNotaEmailGerentes:
            type: text
            nullable: true
            column: te_nota_email_gerentes
        csAbreJanelaPatr:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: cs_abre_janela_patr
        idDefaultBodyBgcolor:
            type: string
            length: 10
            fixed: true
            nullable: false
            column: id_default_body_bgcolor
        teExibeGraficos:
            type: string
            length: 100
            fixed: true
            nullable: false
            column: te_exibe_graficos
        nuPortaSrcacic:
            type: string
            length: 5
            fixed: true
            nullable: false
            column: nu_porta_srcacic
        teUsbFilter:
            type: text
            nullable: false
            column: te_usb_filter
        dtDebug:
            type: string
            length: 1
            fixed: true
            nullable: true
            column: dt_debug
    oneToOne:
        idLocal:
            targetEntity: Local
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_local:
                    referencedColumnName: id_local
            orphanRemoval: false
    lifecycleCallbacks: {  }
