Cacic\CommonBundle\Entity\Local:
    type: entity
    table: local
    repositoryClass: Cacic\CommonBundle\Entity\LocalRepository
    fields:
        idLocal:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_local
            generator:
                strategy: IDENTITY
        nmLocal:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nm_local
        sgLocal:
            type: string
            length: 20
            fixed: true
            nullable: false
            column: sg_local
        teObservacao:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_observacao
        teDebugging:
            type: text
            nullable: true
            column: te_debugging
        dtDebug:
            type: string
            length: 8
            fixed: true
            nullable: true
            column: dt_debug
    oneToMany:
        usuarios:
            targetEntity: Usuario
            mappedBy: idLocal
        redes:
            targetEntity: Rede
            mappedBy: idLocal
    lifecycleCallbacks: {  }
