Cacic\CommonBundle\Entity\So:
    type: entity
    table: so
    repositoryClass: Cacic\CommonBundle\Entity\SoRepository
    fields:
        idSo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_so
            generator:
                strategy: IDENTITY
        teDescSo:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_desc_so
        sgSo:
            type: string
            length: 20
            fixed: false
            nullable: true
            column: sg_so
        teSo:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: te_so
        inMswindows:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: in_mswindows
    lifecycleCallbacks: {  }
