Cacic\CommonBundle\Entity\SrcacicSessao:
    type: entity
    table: srcacic_sessao
    fields:
        idSrcacicSessao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_srcacic_sessao
            generator:
                strategy: IDENTITY
        dtHrInicioSessao:
            type: datetime
            nullable: false
            column: dt_hr_inicio_sessao
        nmAcessoUsuarioSrv:
            type: string
            length: 30
            fixed: true
            nullable: false
            column: nm_acesso_usuario_srv
        nmCompletoUsuarioSrv:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nm_completo_usuario_srv
        teEmailUsuarioSrv:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: te_email_usuario_srv
        dtHrUltimoContato:
            type: datetime
            nullable: true
            column: dt_hr_ultimo_contato
    manyToOne:
        idComputador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
    lifecycleCallbacks: {  }
