<?php

namespace Cacic\MultiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitesRepository extends EntityRepository
{
}
