<?php

namespace Cacic\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComputadorColetaHistoricoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputadorColetaHistoricoRepository extends EntityRepository
{

    /**
     * Lista histórico do computador
     *
     * @param $limit
     * @param $idComputador
     * @param int $page
     * @return array
     */
    public function listar($limit, $idComputador, $classe, $page = 1) {

        $_dql = "SELECT prop.nmPropertyName,
        cl.nmClassName,
        comp.idComputador,
        c.teClassPropertyValue,
        c.dtHrInclusao,
        ct.idComputadorColeta
        FROM CacicCommonBundle:ComputadorColetaHistorico c
        INNER JOIN CacicCommonBundle:ComputadorColeta ct WITH c.computadorColeta = ct.idComputadorColeta
        INNER JOIN CacicCommonBundle:Computador comp WITH c.computador = comp.idComputador
        INNER JOIN CacicCommonBundle:ClassProperty prop WITH prop.idClassProperty = c.classProperty
        INNER JOIN CacicCommonBundle:Classe cl WITH cl.idClass = prop.idClass
        WHERE c.computador = :idComputador
        AND cl.nmClassName = :nmClassName
        ";

        // Offset results
        $offset = ($page - 1) * $limit;

        return $this->getEntityManager()->createQuery( $_dql )
            ->setMaxResults($limit)
            ->setFirstResult($offset)
            ->setParameter('idComputador', $idComputador)
            ->setParameter('nmClassName', $classe)
            ->getArrayResult();
    }
}
