<?php

namespace Cacic\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComputadorColetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComputadorColetaRepository extends EntityRepository
{
	
	/**
	 * Recupera os dados de coleta referentes ao Computador parametrizado
	 * @param \Cacic\CommonBundle\Entity\Computador $computador
	 */
	public function getDadosColetaComputador( \Cacic\CommonBundle\Entity\Computador $computador )
	{
		$qb = $this->createQueryBuilder('coleta')->select('coleta', 'propriedade', 'classe')
					->innerJoin('coleta.classProperty', 'propriedade')
					->innerJoin('propriedade.idClass', 'classe')
					->where('coleta.computador = (:computador)')
					->setParameter('computador', $computador)
					->orderBy('classe.nmClassName')
					->addOrderBy('propriedade.nmPropertyName');
	
		return $qb->getQuery()->execute();
	}
	
}
