<?php

namespace Cacic\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PropriedadeSoftwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropriedadeSoftwareRepository extends EntityRepository
{

    /**
     * Retorna lista de todas as propriedades coletadas
     *
     * @return mixed
     */

    public function propPorNome( $nmSoftware ) {
        $qb = $this->createQueryBuilder('prop')
            ->select('prop')
            ->innerJoin('CacicCommonBundle:Software', 'sw', 'WITH', 'sw.idSoftware = prop.software')
            ->andWhere('sw.nmSoftware = :nmSoftware')
            ->setParameter('nmSoftware', $nmSoftware);

        return $qb->getQuery()->execute();
    }


    public function softwareByName( $nmSoftware, $idComputador ) {
        $qb = $this->createQueryBuilder('prop')
            ->select('prop')
            ->innerJoin('CacicCommonBundle:classProperty', 'cp', 'WITH', 'prop.classProperty = cp.idClassProperty')
            ->innerJoin('CacicCommonBundle:Software', 'sw', 'WITH', 'sw.idSoftware = prop.software')
            ->andWhere('sw.nmSoftware = :nmSoftware')
            ->andWhere('prop.computador = :idComputador')
            ->setParameter('idComputador', $idComputador)
            ->setParameter('nmSoftware', $nmSoftware);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
