AcaoSo:
    type: entity
    table: acao_so
    oneToOne:
        idAcao:
            targetEntity: Acao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_acao:
                    referencedColumnName: id_acao
            orphanRemoval: false
        idRede:
            targetEntity: Rede
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rede:
                    referencedColumnName: id_rede
            orphanRemoval: false
        idSo:
            targetEntity: So
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_so:
                    referencedColumnName: id_so
            orphanRemoval: false
    lifecycleCallbacks: {  }
