ClassPropertyType:
    type: entity
    table: class_property_type
    fields:
        idClassPropertyType:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_class_property_type
            generator:
                strategy: IDENTITY
        csType:
            type: string
            length: 20
            fixed: true
            nullable: false
            column: cs_type
        teTypeDescription:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: te_type_description
    manyToOne:
        idClassProperty:
            targetEntity: ClassProperty
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class_property:
                    referencedColumnName: id_class_property
            orphanRemoval: false
    lifecycleCallbacks: {  }
