RedeVersaoModulo:
    type: entity
    table: rede_versao_modulo
    fields:
        idRedeVersaoModulo:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_rede_versao_modulo
            generator:
                strategy: IDENTITY
        nmModulo:
            type: string
            length: 100
            fixed: false
            nullable: false
            column: nm_modulo
        teVersaoModulo:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_versao_modulo
        dtAtualizacao:
            type: datetime
            nullable: false
            column: dt_atualizacao
        csTipoSo:
            type: string
            length: 20
            fixed: true
            nullable: false
            column: cs_tipo_so
        teHash:
            type: string
            length: 40
            fixed: false
            nullable: true
            column: te_hash
    oneToOne:
        idRede:
            targetEntity: Rede
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rede:
                    referencedColumnName: id_rede
            orphanRemoval: false
    lifecycleCallbacks: {  }
