Software:
    type: entity
    table: software
    fields:
        idSoftware:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_software
            generator:
                strategy: IDENTITY
        nmSoftware:
            type: string
            length: 150
            fixed: false
            nullable: true
            column: nm_software
        teDescricaoSoftware:
            type: string
            length: 255
            fixed: false
            nullable: true
            column: te_descricao_software
        qtLicenca:
            type: integer
            unsigned: false
            nullable: true
            column: qt_licenca
        nrMidia:
            type: string
            length: 10
            fixed: true
            nullable: true
            column: nr_midia
        teLocalMidia:
            type: string
            length: 30
            fixed: true
            nullable: true
            column: te_local_midia
        teObs:
            type: string
            length: 200
            fixed: false
            nullable: true
            column: te_obs
    manyToOne:
        idTipoSoftware:
            targetEntity: TipoSoftware
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_software:
                    referencedColumnName: id_tipo_software
            orphanRemoval: false
    lifecycleCallbacks: {  }
