SrcacicTransf:
    type: entity
    table: srcacic_transf
    fields:
        idSrcacicTransf:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_srcacic_transf
            generator:
                strategy: IDENTITY
        dtSystemtime:
            type: datetime
            nullable: false
            column: dt_systemtime
        nuDuracao:
            type: float
            nullable: false
            column: nu_duracao
        tePathOrigem:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: te_path_origem
        tePathDestino:
            type: string
            length: 255
            fixed: false
            nullable: false
            column: te_path_destino
        nmArquivo:
            type: string
            length: 127
            fixed: false
            nullable: false
            column: nm_arquivo
        nuTamanhoArquivo:
            type: integer
            unsigned: false
            nullable: false
            column: nu_tamanho_arquivo
        csStatus:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: cs_status
        csOperacao:
            type: string
            length: 1
            fixed: true
            nullable: false
            column: cs_operacao
    manyToOne:
        idSrcacicConexao:
            targetEntity: SrcacicConexao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_srcacic_conexao:
                    referencedColumnName: id_srcacic_conexao
            orphanRemoval: false
    lifecycleCallbacks: {  }
