TipoLicenca:
    type: entity
    table: tipo_licenca
    fields:
        idTipoLicenca:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_tipo_licenca
            generator:
                strategy: IDENTITY
        teTipoLicenca:
            type: string
            length: 20
            fixed: true
            nullable: false
            column: te_tipo_licenca
    lifecycleCallbacks: {  }
