UnidOrganizacionalNivel1:
    type: entity
    table: unid_organizacional_nivel1
    fields:
        idUnidOrganizacionalNivel1:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_unid_organizacional_nivel1
            generator:
                strategy: IDENTITY
        nmUnidOrganizacionalNivel1:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: nm_unid_organizacional_nivel1
        teEnderecoUon1:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: te_endereco_uon1
        teBairroUon1:
            type: string
            length: 30
            fixed: true
            nullable: true
            column: te_bairro_uon1
        teCidadeUon1:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: te_cidade_uon1
        teUfUon1:
            type: string
            length: 2
            fixed: true
            nullable: true
            column: te_uf_uon1
        nmResponsavelUon1:
            type: string
            length: 80
            fixed: false
            nullable: true
            column: nm_responsavel_uon1
        teEmailResponsavelUon1:
            type: string
            length: 50
            fixed: false
            nullable: true
            column: te_email_responsavel_uon1
        nuTel1ResponsavelUon1:
            type: string
            length: 10
            fixed: true
            nullable: true
            column: nu_tel1_responsavel_uon1
        nuTel2ResponsavelUon1:
            type: string
            length: 10
            fixed: true
            nullable: true
            column: nu_tel2_responsavel_uon1
    lifecycleCallbacks: {  }
