Patrimonio:
    type: entity
    table: patrimonio
    fields:
        idPatrimonio:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_patrimonio
            generator:
                strategy: IDENTITY
        dtHrAlteracao:
            type: datetime
            nullable: false
            column: dt_hr_alteracao
        teLocalizacaoComplementar:
            type: string
            length: 100
            fixed: true
            nullable: true
            column: te_localizacao_complementar
        teInfoPatrimonio1:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio1
        teInfoPatrimonio2:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio2
        teInfoPatrimonio3:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio3
        teInfoPatrimonio4:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio4
        teInfoPatrimonio5:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio5
        teInfoPatrimonio6:
            type: string
            length: 20
            fixed: true
            nullable: true
            column: te_info_patrimonio6
        idUnidOrganizacionalNivel1:
            type: integer
            unsigned: false
            nullable: false
            column: id_unid_organizacional_nivel1
    manyToOne:
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idUnidOrganizacionalNivel1a:
            targetEntity: UnidOrganizacionalNivel1a
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_unid_organizacional_nivel1a:
                    referencedColumnName: id_unid_organizacional_nivel1a
            orphanRemoval: false
        idComputador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
        idUnidOrganizacionalNivel2:
            targetEntity: UnidOrganizacionalNivel2
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_unid_organizacional_nivel2:
                    referencedColumnName: id_unid_organizacional_nivel2
            orphanRemoval: false
    lifecycleCallbacks: {  }
