SrcacicAction:
    type: entity
    table: srcacic_action
    fields:
        idSrcacicAction:
            id: true
            type: integer
            unsigned: true
            nullable: false
            column: id_srcacic_action
            generator:
                strategy: IDENTITY
        dtHrAction:
            type: datetime
            nullable: false
            column: dt_hr_action
        teAction:
            type: string
            length: 50
            fixed: false
            nullable: false
            column: te_action
        teParam1:
            type: text
            nullable: false
            column: te_param1
        teParam2:
            type: text
            nullable: true
            column: te_param2
        teFlag:
            type: integer
            unsigned: false
            nullable: false
            column: te_flag
    manyToOne:
        idSrcacicConexao:
            targetEntity: SrcacicConexao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_srcacic_conexao:
                    referencedColumnName: id_srcacic_conexao
            orphanRemoval: false
    lifecycleCallbacks: {  }
