SrcacicConexao:
    type: entity
    table: srcacic_conexao
    fields:
        idSrcacicConexao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_srcacic_conexao
            generator:
                strategy: IDENTITY
        idUsuarioCli:
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario_cli
        teNodeAddressCli:
            type: string
            length: 17
            fixed: true
            nullable: false
            column: te_node_address_cli
        teDocumentoReferencial:
            type: string
            length: 60
            fixed: false
            nullable: false
            column: te_documento_referencial
        idSoCli:
            type: integer
            unsigned: false
            nullable: false
            column: id_so_cli
        teMotivoConexao:
            type: text
            nullable: false
            column: te_motivo_conexao
        dtHrInicioConexao:
            type: datetime
            nullable: false
            column: dt_hr_inicio_conexao
        dtHrUltimoContato:
            type: datetime
            nullable: false
            column: dt_hr_ultimo_contato
    manyToOne:
        idSrcacicSessao:
            targetEntity: SrcacicSessao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_srcacic_sessao:
                    referencedColumnName: id_srcacic_sessao
            orphanRemoval: false
    lifecycleCallbacks: {  }
