#!/bin/sh
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
	pid=`ps -Af | grep -m 1 /usr/share/pycacic/cacic.py | grep -v grep | tr -s " " " " | cut -f2 -d" "`
	if [ "$pid" != "" ]; then
		#echo "Matando: ($pid)"
		kill $pid
	fi
	pid=`ps -Af | grep -m 1 /usr/share/pycacic/gui_pycacic.py | grep -v grep | tr -s " " " " | cut -f2 -d" "`
	if [ "$pid" != "" ]; then
		#echo "Matando: ($pid)"
		kill $pid
	fi
	rm -Rf /usr/share/pycacic
fi
