Cacic\CommonBundle\Entity\Local:
    properties:
        nmLocal:
            - NotBlank: ~
            - MaxLength: 100
        sgLocal:
            - NotBlank: ~
            - MaxLength: 20

Cacic\CommonBundle\Entity\Usuario:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nmUsuarioAcesso
    properties:
        idLocal:
            - NotNull: ~
        nmUsuarioAcesso:
            - NotBlank: ~
            - MaxLength: 20
        nmUsuarioCompleto:
            - NotBlank: ~
            - MaxLength: 60
        idGrupoUsuarios:
            - NotNull: ~

Cacic\CommonBundle\Entity\ServidorAutenticacao:
    properties:
        nmServidorAutenticacao:
            - NotBlank: ~
            - MaxLength: 60
        nmServidorAutenticacaoDns:
            - NotBlank: ~
            - MaxLength: 60
        teIpServidorAutenticacao:
            - NotBlank: ~
            - Ip: ~
        nuPortaServidorAutenticacao:
            - NotBlank: ~
            - MaxLength: 5
        idTipoProtocolo:
            - NotBlank: ~
            - MaxLength: 20
        nuVersaoProtocolo:
            - NotBlank: ~
            - MaxLength: 10
        teAtributoIdentificador:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoRetornaNome:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoRetornaEmail:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoValorStatusContaValida:
            - NotBlank: ~
            - MaxLength: 100
        inAtivo:
            - Choice:
                choices:  [S, N]

Cacic\CommonBundle\Entity\Rede:
    properties:
        nmRede:
            - MaxLength: 30
        teMascaraRede:
            - NotBlank: ~
            - MaxLength: 20
        teServCacic:
            - NotBlank: ~
            - MaxLength: 20
        teServCacic:
            - NotBlank: ~
        teServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        teServUpdates:
            - NotBlank: ~
        nuPortaServUpdates:
            - NotBlank: ~
            - MaxLength: 5
        nuLimiteFtp:
            - NotBlank: ~
            - MaxLength: 5
        nmUsuarioLoginServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        teSenhaLoginServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        nmUsuarioLoginServUpdatesGerente:
            - NotBlank: ~
            - MaxLength: 20
        teSenhaLoginServUpdatesGerente:
            - NotBlank: ~
            - MaxLength: 20
        tePathServUpdates:
            - NotBlank: ~
            - MaxLength: 20

Cacic\CommonBundle\Entity\So:
    properties:
        teDescSo:
            - NotBlank: ~
            - MaxLength: 30
        sgSo:
            - NotBlank: ~
            - MaxLength: 30
        teSo:
            - NotNull: ~
            - Maxlength: 10

Cacic\CommonBundle\Entity\Aplicativo:
    properties:
        dtAtualizacao:
            - NotBlank: ~
            - Type: \DateTime

Cacic\CommonBundle\Entity\Softwares:
    properties:
        nmSoftware:
            - NotBlank: ~
            - MaxLength: 30
        teDescricaoSoftware:
            - NotBlank: ~
            - MaxLength: 30
        qtLicenca:
            - Notblank: ~
            - MaxLength: 10
        nrMidia:
            - NotBlank: ~
            - MaxLength: 10
        teLocalMidia:
            - NotBlank: ~
            - MaxLength: 30
        teObs:
            - MaxLength: 30

Cacic\CommonBundle\Entity\Softwares:
    properties:
