Cacic\CommonBundle\Entity\Locais:
    properties:
        nmLocal:
            - NotBlank: ~
            - MaxLength: 100
        sgLocal:
            - NotBlank: ~
            - MaxLength: 20

Cacic\CommonBundle\Entity\Usuarios:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: nmUsuarioAcesso
    properties:
        idLocal:
            - NotNull: ~
        nmUsuarioAcesso:
            - NotBlank: ~
            - MaxLength: 20
        nmUsuarioCompleto:
            - NotBlank: ~
            - MaxLength: 60
        idGrupoUsuarios:
            - NotNull: ~

Cacic\CommonBundle\Entity\ServidoresAutenticacao:
    properties:
        nmServidorAutenticacao:
            - NotBlank: ~
            - MaxLength: 60
        nmServidorAutenticacaoDns:
            - NotBlank: ~
            - MaxLength: 60
        teIpServidorAutenticacao:
            - NotBlank: ~
            - Ip: ~
        nuPortaServidorAutenticacao:
            - NotBlank: ~
            - MaxLength: 5
        idTipoProtocolo:
            - NotBlank: ~
            - MaxLength: 20
        nuVersaoProtocolo:
            - NotBlank: ~
            - MaxLength: 10
        teAtributoIdentificador:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoRetornaNome:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoRetornaEmail:
            - NotBlank: ~
            - MaxLength: 100
        teAtributoValorStatusContaValida:
            - NotBlank: ~
            - MaxLength: 100
        teObservacao:
            - NotBlank: ~
        inAtivo:
            - Choice:
                choices:  [S, N]

Cacic\CommonBundle\Entity\Redes:
    properties:
        nmRede:
            - NotBlank: ~
            - MaxLength: 30
        teMascaraRede:
            - NotBlank: ~
            - MaxLength: 20
        teServCacic:
            - NotBlank: ~
            - MaxLength: 20
        selTeServCacic:
            - NotBlank: ~
        teServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        selTeServUpdates:
            - NotBlank: ~
        nuPortaServUpdates:
            - NotBlank: ~
            - MaxLength: 5
        nuLimiteFtp:
            - NotBlank: ~
            - MaxLength: 5
        nmUsuarioLoginServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        teSenhaLoginServUpdates:
            - NotBlank: ~
            - MaxLength: 20
        nmUsuarioLoginServUpdatesGerente:
            - NotBlank: ~
            - MaxLength: 20
        teSenhaLoginServUpdatesGerente:
            - NotBlank: ~
            - MaxLength: 20
        tePathServUpdates:
            - NotBlank: ~
            - MaxLength: 20