Cacic\CommonBundle\Entity\Locais:
    properties:
        nmLocal:
            - NotBlank: ~
            - MaxLength: 100
        sgLocal:
            - NotBlank: ~
            - MaxLength: 20

Cacic\CommonBundle\Entity\Usuarios:
    properties:
        idLocal:
            - NotNull: ~
        nmUsuarioAcesso:
            - NotBlank: ~
            - MaxLength: 20
        nmUsuarioCompleto:
            - NotBlank: ~
            - MaxLength: 60
        idGrupoUsuarios:
            - NotNull: ~