cacic_relatorio_autorizacoes:
    pattern: /relatorio/autorizacoes
    defaults: { _controller: CacicRelatorioBundle:Default:autorizacoes }

cacic_relatorio_compartilhamentos:
    pattern: /relatorio/compartilhamentos
    defaults: { _controller: CacicRelatorioBundle:Default:compartilhamentos }

cacic_relatorio_tcpIp:
    pattern: /relatorio/tcpip
    defaults: { _controller: CacicRelatorioBundle:Default:tcpIp }

cacic_relatorio_variaveisAmbiente:
    pattern: /relatorio/variaveisambiente
    defaults: { _controller: CacicRelatorioBundle:Default:variaveisAmbiente }

cacic_relatorio_patrimonio:
    pattern: /relatorio/patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonio }

cacic_relatorio_software_officescan:
    pattern: /relatorio/software/officescan
    defaults: { _controller: CacicRelatorioBundle:Software:officeScan }

cacic_relatorio_software_infoSoftwareBasico:
    pattern: /relatorio/software/basico
    defaults: { _controller: CacicRelatorioBundle:Software:infoSoftwareBasico }

cacic_relatorio_software_inventariados:
    pattern: /relatorio/software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariados }

cacic_relatorio_software_licensiados:
    pattern: /relatorio/software/licensiados
    defaults: { _controller: CacicRelatorioBundle:Software:licensiados }

cacic_relatorio_software_orgao:
    pattern: /relatorio/software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgao }

cacic_relatorio_software_aquisicoes:
    pattern: /relatorio/software/aquisicoes
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoes }

cacic_relatorio_software_adquiridos:
    pattern: /relatorio/software/adquiridos
    defaults: { _controller: CacicRelatorioBundle:Software:adquiridos }

cacic_relatorio_software_compra:
    pattern: /relatorio/software/compra
    defaults: { _controller: CacicRelatorioBundle:Software:compra }

cacic_relatorio_software_tipo:
    pattern: /relatorio/software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipo }

cacic_relatorio_software_ultimos:
    pattern: /relatorio/software/ultimos
    defaults: { _controller: CacicRelatorioBundle:Software:ultimos }

cacic_relatorio_software_suspeitos:
    pattern: /relatorio/software/suspeitos
    defaults: { _controller: CacicRelatorioBundle:Software:suspeitos }

cacic_relatorio_software_historicoEstacao:
    pattern: /relatorio/software/historicoestacao
    defaults: { _controller: CacicRelatorioBundle:Software:historicoEstacao }

cacic_relatorio_software_naoVinculados:
    pattern: /relatorio/software/naovinculados
    defaults: { _controller: CacicRelatorioBundle:Software:naoVinculados }

cacic_relatorio_software_genericos:
    pattern: /relatorio/software/genericos
    defaults: { _controller: CacicRelatorioBundle:Software:genericos }